{"error_result": {"reason": "backendError", "message": "Error encountered during execution. Retrying may solve the problem."}, "errors": [{"reason": "backendError", "message": "Error encountered during execution. Retrying may solve the problem."}], "job_start": "2022-09-03T06:56:27.669000Z", "job_end": "2022-09-03T06:56:27.669000Z", "job_id": "axie_contract_call_safe_transfer_from_945be7eae9433b345538ef96f1485d3f_jsonl"}